repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.20
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: flake8
      additional_dependencies: [
        'flake8-docstrings',
        'pep8-naming'
      ]
      args: [
        '--config=tox.ini',
        '--docstring-convention=google'
      ]
